---
permalink: concept-create-and-manage-backup-jobs-in-snapmanager-for-hyper-v.html 
sidebar: sidebar 
keywords: create, monitor, on-demand, backup, manage, schedule, snapmanager, hyper-v, creating, managing, application, crash 
summary: SnapManager for Hyper-V에서 필요 시 백업 또는 관리되는 예약 백업을 생성하고 모니터링할 수 있습니다 
---
= SnapManager for Hyper-V에서 백업 작업을 생성하고 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
SnapManager for Hyper-V에서 필요 시 백업 또는 관리되는 예약 백업을 생성하고 모니터링할 수 있습니다 또한 SnapManager for Hyper-V를 사용하여 두 가지 유형의 백업 작업을 수행할 수 있습니다. 즉, 애플리케이션 정합성 보장 및 충돌 정합성이 보장됩니다.



== SnapManager for Hyper-V 백업 정보

필요 시 백업 작업을 생성하여 원하는 시간에 실행하거나 데이터 세트에 연결된 정책을 사용하여 예약된 백업 작업을 생성할 수 있습니다. 필요 시 백업 작업에는 보존 및 복제 정책과 백업 전/후에 실행할 스크립트가 포함될 수 있습니다. 예약된 백업 작업을 구성하는 정책을 생성, 수정, 보기 및 삭제할 수 있습니다.



== SnapManager for Hyper-V가 수행할 수 있는 백업 작업 유형

SnapManager for Hyper-V에서는 애플리케이션 정합성 보장 및 충돌 정합성 보장이라는 두 가지 유형의 백업 작업을 수행할 수 있습니다.



== 애플리케이션 정합성이 보장되는 백업 작업

애플리케이션 정합성이 보장되는 백업 작업은 철저하고 안정적이며 리소스가 많이 필요합니다. 이 작업은 Microsoft VSS(Volume Shadow Copy Service)와 함께 수행하여 스냅샷 복사본을 생성하기 전에 VM에서 실행 중인 각 애플리케이션을 중지하도록 합니다. 이 백업 방법은 애플리케이션 데이터의 일관성을 보장합니다. VM 및 VM에서 실행 중인 애플리케이션을 복원하는 데 사용할 수 있습니다. 하지만 애플리케이션 정합성이 보장되는 백업 작업은 시간이 오래 걸리고 복잡할 수 있습니다.



== 충돌 시에도 정합성 보장 백업 작업

충돌 시에도 정합성 보장 백업 작업은 데이터 세트에 포함된 VM에서 사용하는 모든 LUN의 신속한 스냅샷 복사본입니다. 그 결과 생성된 백업 복제본은 충돌하거나 갑자기 전원이 꺼진 VM의 데이터 캡처와 유사합니다. 충돌 시에도 정합성이 보장되는 백업 작업을 통해 데이터를 빠르게 캡처할 수 있지만 충돌 시에도 정합성이 보장되는 백업에서 VM을 복구해야 합니다. 충돌 시에도 정합성이 보장되는 백업 작업은 애플리케이션 정합성이 보장되는 백업 작업을 대체하기 위한 것이 아닙니다.



== SnapManager for Hyper-V 백업 요구 사항 및 제한 사항

Hyper-V 백업을 위한 SnapManager의 요구 사항 및 제한 사항을 숙지해야 합니다.

* MetroCluster 구성에서 스위치오버 또는 스위치백 작업을 수행하는 경우에는 백업 및 복원 작업이 지원되지 않습니다. 백업 및 복원 작업과 스위치오버 또는 스위치백 작업이 동시에 실행되는 경우 Windows Server 2012 R2 시스템에서 VM의 .vhd 파일 형식이 '.avhdx'로 변경될 수 있습니다. VM은 이 변경의 영향을 받지 않습니다.
* 분산 애플리케이션 정합성 보장 백업 옵션을 사용하면 파트너 클러스터 노드에서 실행되는 여러 VM이 백업 노드에서 생성된 단일 하드웨어 스냅샷 사본에서 일관성을 유지할 수 있습니다. 이 옵션은 Windows 페일오버 클러스터의 여러 노드에서 CSV 2.0 Windows 볼륨에서 실행되는 모든 VM에 대해 지원됩니다.
* 7-Mode에서 운영 중인 경우 애플리케이션 정합성이 보장되는 백업 작업에서는 VSS Hardware Provider를 사용하여 2개의 스냅샷 복사본을 생성합니다. 스냅샷 복사본을 스냅샷_이름 과 스냅샷_이름_백업 이라고 합니다. 두 개의 Snapshot 복사본이 VSS 백업 중에 쉽게 자동 복구되도록 만들어집니다.
* 클러스터 환경에서는 애플리케이션 정합성이 보장되는 백업에는 자동 복구 프로세스에 대해 하나의 스냅샷 복사본만 필요합니다. SIS 클론은 자동 복구를 수행하는 데 활용되며, 자동 복구가 완료되면 첫 번째 Snapshot 복사본('sapshot_name')이 삭제됩니다.
* VM의 각 Windows 볼륨에는 최소 300MB의 사용 가능한 디스크 공간이 있어야 합니다. 여기에는 VHD, iSCSI LUN 및 VM에 연결된 Pass-through 디스크에 해당하는 Windows 볼륨이 포함됩니다.
* 충돌 시에도 정합성 보장 백업 작업에서는 항상 하나의 스냅샷 복사본만 생성됩니다. VSS 통합은 제공하지 않습니다.
* 충돌 시에도 정합성이 보장되는 여러 백업 작업을 동시에 실행할 수 있습니다. 충돌 시에도 정합성 보장 백업 작업은 애플리케이션 정합성 보장 백업 작업과 동시에 실행할 수 있습니다.
* 충돌 시에도 정합성 보장 백업 작업에는 저장된 상태 백업 허용이 적용되지 않습니다.

