---
permalink: concept-overview-of-vss-components.html 
sidebar: sidebar 
keywords: microsoft, windows, server, volume, shadow, copy, service, vss, coordinate, data, backup, application, storage, management, consisten, backup 
summary: 'Microsoft Windows Server VSS(Volume Shadow Copy Service)를 사용하면 데이터 서버, 백업 애플리케이션 및 스토리지 관리 소프트웨어를 조정하여 정합성 보장 백업의 생성 및 관리를 지원할 수 있습니다.' 
---
= VSS 구성 요소
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Microsoft Windows Server VSS(Volume Shadow Copy Service)를 사용하면 데이터 서버, 백업 애플리케이션 및 스토리지 관리 소프트웨어를 조정하여 정합성 보장 백업의 생성 및 관리를 지원할 수 있습니다.

VSS는 스냅샷 복사본 기반 백업 및 복원 작업을 조정하며 다음과 같은 구성 요소를 포함합니다.

* * VSS 요청자 *
+
VSS 요청자는 SnapManager for Hyper-V 또는 NTBackup과 같은 백업 애플리케이션입니다. VSS 백업 및 복원 작업을 시작합니다. 요청자는 또한 해당 요청자가 시작하는 백업에 대한 스냅샷 복사본 속성을 지정합니다.

* * VSS 기록기 *
+
VSS 기록기는 스냅샷 복사본에 캡처될 데이터를 소유하고 관리합니다. Microsoft Hyper-V VSS 작성기는 VSS 작성기의 예입니다.

* VSS 공급자 *
+
VSS 공급자는 스냅샷 복사본을 생성하고 관리합니다. 공급자는 하드웨어 공급자 또는 소프트웨어 공급자가 될 수 있습니다.

+
** 하드웨어 공급자는 스토리지 어레이별 스냅샷 복사 및 클론 복제 기능을 VSS 프레임워크에 통합합니다.
+
ONTAP VSS Hardware Provider는 Data ONTAP를 실행하는 SnapDrive 서비스와 스토리지 시스템을 VSS 프레임워크에 통합합니다.

+

NOTE: ONTAP VSS Hardware Provider는 SnapDrive 소프트웨어 설치의 일부로 자동으로 설치됩니다.

** 소프트웨어 공급자는 Windows 시스템에서 실행 중인 소프트웨어에서 스냅샷 복사본 또는 클론 복제 기능을 구현합니다.
+

NOTE: ONTAP VSS 하드웨어 공급자가 제대로 작동하는지 확인하려면 Data ONTAP LUN에서 VSS 소프트웨어 공급자를 사용하지 마십시오. VSS 소프트웨어 공급자를 사용하여 Data ONTAP LUN에 스냅샷 복사본을 생성하는 경우 VSS 하드웨어 공급자를 사용하여 해당 LUN을 삭제할 수 없습니다.




