---
permalink: concept-snapmanager-for-hyper-v-limitations.html 
sidebar: sidebar 
keywords: important, understand, snapmanager, hyper-v, limitation 
summary: 일부 기능은 Hyper-V의 경우 SnapManager 2.1 이상에서 지원되지 않는다는 점을 이해해야 합니다 
---
= SnapManager for Hyper-V 제한 사항 목록입니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
일부 기능은 SnapManager 2.1 이상에서 Hyper-V에 지원되지 않는다는 점을 이해해야 합니다.

* 백업 및 복원 작업의 취소, 일시 중지 및 다시 재개는 지원되지 않습니다.
* 정책은 데이터 세트 간에 복사할 수 없습니다.
* 역할 기반 액세스 제어(RBAC)는 지원되지 않습니다.
* SnapManager for Hyper-V VSS(Volume Shadow Copy Service) 백업 작업에서 VHD(가상 하드 디스크)를 제외하는 것은 지원되지 않습니다.
* 백업 사본에서 단일 파일 복원이 기본적으로 지원되지 않습니다.
* 크로스 버전 관리는 지원되지 않습니다. 예를 들어, 클라이언트 콘솔 1.2를 사용하여 Hyper-V용 SnapManager 2.0을 관리할 수 없으며 반대의 경우도 마찬가지입니다.
* Hyper-V 가상 머신(VM)의 복원을 시작하고 동일한 VM의 다른 백업 또는 복원이 진행 중인 경우 시도가 실패합니다.
* 충돌 시에도 정합성이 보장되는 백업 복제본에서 삭제된 VM의 복원은 Windows Server 2012에만 지원됩니다.
* 페일오버 클러스터의 다른 노드에서 여러 버전의 SnapManager for Hyper-V를 실행하는 것은 지원되지 않습니다.
* Hyper-V에 대해 SnapManager 2.1에서 되돌리는 것은 지원되지 않습니다.
* 백업 또는 복구 중에 사용자가 클러스터 소유권 노드를 변경하면 가상 머신의 백업 또는 복원 작업이 지원되지 않습니다.
* 혼합 모드 백업(CSV 2.0 볼륨 및 SMB 공유에 파일이 포함된 가상 머신)은 지원되지 않습니다.
* Windows Server 2012를 사용하여 VM의 스토리지를 다른 위치로 마이그레이션한 후에는 마이그레이션 전에 만든 백업 복사본에서 해당 VM을 복원할 수 없습니다.
* Windows Server 2012의 경우 백업 세트에 CSV(Cluster Shared Volume)와 공유 디스크가 모두 포함된 백업 작업을 수행할 수 없습니다.
* 저장소 연결 설정 관리 를 구성할 때 RPC(원격 프로시저 호출) 프로토콜을 사용할 수 없습니다. HTTP 및 HTTPS 프로토콜만 사용할 수 있습니다.
* NAS 스토리지에 저장된 가상 머신(VM)의 애플리케이션 정합성이 보장되는 백업을 생성하는 것은 Windows Server 2012 Hyper-V 운영 체제에서 지원되지 않습니다.
+
이 제한은 충돌 시에도 정합성 보장 백업에는 적용되지 않습니다. 파일 공유 섀도 복사본 서비스는 포함되지 않는 무료 Hyper-V 서버에만 적용됩니다.

* VM의 가상 스위치 이름은 운영 및 보조 Windows 호스트의 가상 스위치 이름과 정확히 같아야 합니다.
* SMB 3.0을 통해 Hyper-V VM을 구축할 경우 백업 및 복원 작업에 FlexClone 라이센스가 필요합니다.
* 복구 작업에 지원되는 최대 LUN 크기는 14TB입니다.
* 다음 Hyper-V Server는 애플리케이션 정합성이 보장되는 VM 백업을 지원하지 않습니다.
+
** Microsoft Hyper-V Server 2016(무료 에디션)
** Microsoft Hyper-V Server 2019(무료 버전)
+
이 제한은 충돌 시에도 정합성 보장 백업 또는 다음 Windows 플랫폼에는 적용되지 않습니다.

** Microsoft Windows Server 2016 Standard 및 Datacenter Edition
** Microsoft Windows Server 2019 Standard 및 Datacenter Edition



