---
permalink: concept-configure-snapmanager-for-hyper-v-for-failover.html 
sidebar: sidebar 
keywords: enable, snapmanager, hyper-v, implementation, disaster, recovery, primary, secondary, host, powershell, failover, configure, configuring 
summary: 재해 복구를 위해 SnapManager for Hyper-V 구현을 완벽하게 설정하려면 운영 호스트와 보조 호스트가 동일한 구성을 가지고 있고 PowerShell만 사용하여 재해 복구를 수행할 수 있는지 확인해야 합니다. 
---
= 페일오버에 Hyper-V용 SnapManager를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
재해 복구를 위해 SnapManager for Hyper-V 구현을 완벽하게 설정하려면 운영 호스트와 보조 호스트가 동일한 구성을 가지고 있고 PowerShell만 사용하여 재해 복구를 수행할 수 있는지 확인해야 합니다.

다음 유형의 설정은 재해 복구를 지원합니다.

* 독립 실행형 운영 호스트 및 독립 실행형 보조 Hyper-V 호스트
* 클러스터형 운영 및 보조 Hyper-V 호스트
* 운영 및 보조 Hyper-V 호스트의 CSV(Cluster Shared Volume


예를 들어 기본 호스트의 클러스터 가상 머신(VM)을 클러스터 VM으로 복구하고 전용(독립 실행형) VM을 전용 VM으로 복구해야 하며 CSV VM을 CSV VM으로 복구해야 합니다.

보조 호스트의 LUN은 운영 호스트의 LUN과 동일한 방식으로 접속되어야 합니다. 즉, LUN 유형(전용, 공유 또는 CSV) 및 드라이브 문자, 마운트 지점 또는 CSV 재분석 지점은 운영 호스트와 보조 호스트에서 동일해야 합니다. SAN 복구 작업을 대체 경로 위치에 수행하면 보조 위치의 LUN 복원 작업에 대해 다른 드라이브 문자를 지정할 수 있습니다.


NOTE: 드라이브 문자 또는 CSV 및 볼륨 마운트 지점이 지원됩니다.

다음 예에서는 기본 재해 복구 설정을 보여 줍니다.

* 사이트 A(운영)에는 스토리지 시스템과 독립 실행형 Hyper-V 호스트 시스템 또는 Hyper-V 호스트 클러스터가 포함됩니다.
+
이러한 호스트에서 실행 중인 VM은 Data ONTAP 스토리지에 상주합니다.

* 사이트 B(보조)에는 스토리지 시스템과 Hyper-V 호스트 또는 클러스터(운영 호스트와 동일)가 포함됩니다.
* Windows용 SnapDrive와 Hyper-V용 SnapManager는 사이트 A와 B 모두에 설치됩니다
* SnapMirror 관계는 사이트 A에서 사이트 B로 초기화됩니다
* 사이트 A에서 Hyper-V용 SnapManager에 추가된 Hyper-V 호스트 또는 클러스터와 VM은 SnapManager for Hyper-V를 사용하여 백업됩니다
+
백업 확인 후 SnapMirror를 업데이트하는 정책 각 백업 후 보조 사이트가 VM의 새 스냅샷 복사본과 SnapInfo 복사본으로 업데이트됩니다.


