---
settings:
  name: SnapManager for Hyper-V
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: 홈
    url: "/index.html"
  - title: SnapManager for Hyper-V가 무엇인지
    url: "/concept_what_snapmanager_for_hyper_v_is.html"
    entries:
    - title: SnapManager for Hyper-V의 기능
      url: "/concept_what_you_can_do_with_snapmanager_for_hyper_v.html"
    - title: SnapManager for Hyper-V 제한 사항 목록입니다
      url: "/concept_snapmanager_for_hyper_v_limitations.html"
    - title: 데이터 관리 개념
      url: "/concept_data_management_concepts.html"
  - title: Hyper-V용 SnapManager 설치 요구 사항 목록
    url: "/reference_list_of_requirements_for_installing_snapmanager_for_hyper_v.html"
    entries:
    - title: ONTAP용 SnapManager Hyper-V 라이센스
      url: "/reference_snapmanager_for_hyper_v_licensing_for_ontap.html"
    - title: Hyper-V 상위 호스트 요구 사항
      url: "/reference_hyper_v_parent_host_requirements.html"
    - title: Windows Server 환경에 대한 핫픽스 요구 사항
      url: "/reference_hotfix_requirements_for_windows_server_environments.html"
    - title: 라이센스 요구 사항
      url: "/reference_license_requirements.html"
    - title: 원격 호스트 설치 마법사 사용에 대한 요구 사항
      url: "/reference_requirements_for_remote_host_install.html"
  - title: Hyper-V용 SnapManager 설치
    url: "/concept_installing_snapmanager_for_hyper_v.html"
    entries:
    - title: Hyper-V용 SnapManager 다운로드 중
      url: "/task_downloading_snapmanager_for_hyper_v.html"
    - title: Windows용 SnapDrive 및 Hyper-V용 SnapManager 설치 순서
      url: "/concept_installation_order_for_snapdrive_for_windows_and_snapmanager_for_hyper_v.html"
    - title: Hyper-V용 SnapManager 설치
      url: "/task_installing_snapmanager_for_hyper_v.html"
    - title: 노드나 호스트에 SnapManager for Hyper-V를 원격으로 설치 또는 제거합니다
      url: "/task_remotely_installing_or_uninstalling_snapmanager_for_hyper_v_on_nodes.html"
    - title: 자동 설치를 위한 명령줄 스위치 목록 및 설명
      url: "/reference_command_line_switch_descriptions.html"
  - title: Windows에서 Hyper-V용 SnapManager 제거
    url: "/concept_uninstalling_snapmanager_for_hyper_v_on_windows.html"
    entries:
    - title: SnapManager for Hyper-V 제거 중
      url: "/task_uninstalling_snapmanager_for_hyper_v.html"
  - title: Hyper-V용 SnapManager 구성
    url: "/concept_configuring_snapmanager_for_hyper_v.html"
    entries:
    - title: 대시보드 설정
      url: "/concept_dashboard_settings.html"
    - title: 호스트 구성
      url: "/concept_configuring_hosts.html"
      entries:
      - title: Hyper-V 상위 호스트 또는 호스트 클러스터를 추가하기 위한 요구 사항
        url: "/reference_requirements_for_adding_a_hyper_v_parent_host_or_host_cluster.html"
      - title: Hyper-V 상위 호스트 또는 호스트 클러스터 추가
        url: "/task_adding_a_hyper_v_parent_host_or_host_cluster.html"
      - title: 스토리지 접속 설정 관리
        url: "/task_managing_storage_connection_settings.html"
      - title: Hyper-V 상위 호스트 또는 호스트 클러스터 보기
        url: "/task_viewing_a_hyper_v_parent_host_or_host_cluster.html"
      - title: 가상 머신 보기
        url: "/task_viewing_a_virtual_machine.html"
      - title: Hyper-V 작업을 위한 SnapManager용 Hyper-V 가상 머신 마이그레이션
        url: "/task_migrating_a_hyper_v_virtual_machine_to_support_snapmanager_for_hyper_v_operations.html"
      - title: 호스트 및 데이터 세트 구성 정보 가져오기 또는 내보내기
        url: "/task_importing_or_exporting_host_and_dataset_configuration_information.html"
      - title: Hyper-V 상위 호스트 또는 상위 호스트 클러스터 제거
        url: "/task_removing_a_hyper_v_parent_host.html"
      - title: 이벤트 알림 설정
        url: "/concept_event_notification_settings.html"
        entries:
        - title: 이메일 알림을 구성하는 중입니다
          url: "/concept_configuring_multiple_recipients_for_email_notifications_in_smhv.html"
      - title: 보고서 경로 설정
        url: "/concept_report_path_settings.html"
    - title: SnapInfo 디렉토리 설정을 구성합니다
      url: "/concept_configuring_snapinfo_directory_settings.html"
      entries:
      - title: SnapInfo LUN 설정
        url: "/task_setting_up_a_snapinfo_lun.html"
      - title: SnapInfo 디렉토리 경로를 변경하는 중입니다
        url: "/task_changing_the_snapinfo_directory_path.html"
    - title: 데이터 세트 구성
      url: "/concept_configuring_datasets.html"
      entries:
      - title: 데이터 세트 생성 요구 사항
        url: "/reference_requirements_for_creating_a_dataset.html"
      - title: 데이터 세트 생성
        url: "/task_creating_a_dataset.html"
      - title: 데이터 세트 수정
        url: "/task_modifying_a_dataset.html"
      - title: 데이터 세트 보기
        url: "/task_viewing_a_dataset.html"
      - title: 데이터 세트 삭제
        url: "/task_deleting_a_dataset.html"
    - title: 정책 구성 중
      url: "/concept_configuring_policies.html"
      entries:
      - title: 데이터 세트에 정책을 추가하기 위한 요구사항
        url: "/reference_requirements_for_adding_policies_to_a_dataset.html"
      - title: 정책 추가
        url: "/task_adding_policies.html"
      - title: 정책을 수정하는 중입니다
        url: "/task_modifying_policies.html"
      - title: 정책 보기
        url: "/task_viewing_policies.html"
      - title: 정책을 삭제하는 중입니다
        url: "/task_deleting_policies.html"
    - title: SMB를 통한 Hyper-V에 대해 SVM 또는 CIFS 서버 구성
      url: "/concept_configuring_svms_or_cifs_servers_for_hyper_v_over_smb.html"
  - title: 보고서 관리
    url: "/concept_report_management.html"
    entries:
    - title: 데이터 세트 보고서 보기
      url: "/task_viewing_a_report.html"
    - title: 호스트 보고서 보기
      url: "/task_viewing_a_host_report.html"
    - title: 보고서 삭제
      url: "/task_deleting_a_report.html"
  - title: VSS 구성 요소
    url: "/concept_overview_of_vss_components.html"
    entries:
    - title: Windows Server 2012 이상에서 CSV 2.0
      url: "/concept_cluster_shared_volume_2_0_architecture.html"
    - title: Windows Server 2012에서 Hyper-V VM을 지원하는 SMB 3.0
      url: "/reference_smb_3_0_support_hyper_v_vms_in_windows_server_2012.html"
    - title: SnapManager for Hyper-V에서 VSS를 사용하는 방법
      url: "/concept_how_snapmanager_for_hyper_v_uses_vss.html"
    - title: ONTAP VSS 하드웨어 공급자 요구 사항
      url: "/concept_ontap_vss_hardware_provider_requirement.html"
    - title: 설치된 VSS 공급자를 보는 중입니다
      url: "/task_viewing_installed_vss_providers.html"
    - title: VSS Hardware Provider가 성공적으로 사용되었는지 확인
      url: "/task_verifying_that_the_vss_hardware_provider_was_used_successfully.html"
  - title: SnapManager for Hyper-V에서 백업 작업 생성 및 관리
    url: "/concept_creating_and_managing_backup_jobs_in_snapmanager_for_hyper_v.html"
    entries:
    - title: 데이터 세트를 수동으로 백업하기 위한 요구 사항입니다
      url: "/reference_requirements_for_manually_backing_up_a_dataset.html"
    - title: SnapManager for Hyper-V가 저장된 상태 백업을 처리하는 방법
      url: "/concept_how_snapmanager_for_hyper_v_handles_saved_state_backups.html"
    - title: 데이터 세트를 수동으로 백업합니다
      url: "/task_manually_backing_up_a_dataset.html"
    - title: 백업 작업 모니터링
      url: "/task_monitoring_backup_jobs.html"
    - title: 백업을 삭제하는 중입니다
      url: "/task_deleting_a_backup.html"
  - title: 백업 복제본에서 가상 머신 복구
    url: "/concept_restoring_a_virtual_machine.html"
    entries:
    - title: 가상 머신 복구 요구 사항
      url: "/reference_requirements_for_restoring_a_virtual_machine.html"
    - title: 백업 복제본에서 가상 머신 복구
      url: "/task_restoring_a_virtual_machine_from_a_backup_copy.html"
  - title: 클러스터 운영 체제 롤링 업그레이드 수행
    url: "/concept_performing_a_cluster_os_rolling_upgrade.html"
    entries:
    - title: 혼합 운영 체제 모드에서 LUN 매핑
      url: "/task_mapping_luns_after_the_windows_server_2016_node_addition.html"
    - title: 모든 노드에서 데이터 세트 및 SnapInfo 업데이트
      url: "/task_updating_the_dataset_and_snapinfo_across_all_nodes.html"
  - title: 재해 복구를 수행하는 중입니다
    url: "/concept_performing_disaster_recovery.html"
    entries:
    - title: Hyper-V 페일오버 기능을 위한 SnapManager 구성
      url: "/concept_configuring_snapmanager_for_hyper_v_for_failover.html"
    - title: 재해 복구 페일오버에서 복구 및 복원
      url: "/task_recovering_and_restoring_from_a_disaster_recovery_failover.html"
    - title: 재해 복구 페일백 후 스토리지 시스템 재구성
      url: "/task_reconfiguring_storage_systems_after_a_disaster_recovery_failback.html"
    - title: 독립 실행형 호스트에 대한 원래 구성 복원
      url: "/task_restoring_the_original_configuration_for_standalone_hosts.html"
    - title: 클러스터된 호스트에 대한 원래 구성을 복원합니다
      url: "/task_restoring_the_original_configuration_for_clustered_hosts.html"
  - title: Hyper-V용 SnapManager 문제 해결
    url: "/concept_snapmanager_for_hyper_v_troubleshooting.html"
    entries:
    - title: 다음 VM에 대한 백업이 실패하였습니다. 온라인 백업 또는 백업 대상 VM을 찾을 수 없기 때문입니다
      url: "/reference_backup_failed_for_the_following_vm_s_since_it_cannot_be_backedup_online_or_no_vm_to_be_found_for_backup.html"
    - title: IVssWriterCallback 인터페이스에 대한 예기치 않은 쿼리 오류. hr=0x80070005, 액세스가 거부되었습니다.
      url: "/reference_unexpected_error_querying_for_the_ivsswritercallback_interface_hr_0x80070005.html"
    - title: 백업 보고서는 보고서 이름에 관리 콘솔 시간대 정보를 사용합니다
      url: "/reference_backup_reports_use_management_console_time_zone_information_in_report_name.html"
    - title: IPv6 전용 환경에서는 백업 및 복원 알림이 전송되지 않습니다
      url: "/reference_backup_and_restore_notifications_not_sent_in_ipv6_only_environments.html"
    - title: 장애 조치 클러스터링 이벤트 ID 5121
      url: "/reference_failover_clustering_event_id_5121.html"
    - title: 복구 작업이 진행 중인 동안 생성된 가상 머신 백업이 잘못되었을 수 있습니다
      url: "/reference_virtual_machine_backups_made_while_a_restore_operation_is_in_progress_might_be_invalid.html"
    - title: 가상 시스템 관리
      url: "/reference_virtual_machine_adding_itself_to_a_dataset.html"
    - title: IPv6 전용 호스트에서는 연결 시간이 길어집니다
      url: "/reference_connection_time_is_longer_with_ipv6_only_host.html"
    - title: '볼륨 섀도 복사본 서비스 오류: 내부 불일치가 감지되었습니다'
      url: "/reference_volume_shadow_copy_service_error_an_internal_inconsistency_was_detected.html"
    - title: 웹 서비스 클라이언트 채널이 시스템 smhv51_81clus의 ConfigurationManagementService 인스턴스에
        연결할 수 없습니다
      url: "/reference_web_service_client_channel_was_unable_to_connect_to_the_configurationmanagementservice_instance_on_machine_smhv51_81clus.html"
    - title: MSI 사용자 정의 속성은 자동 설치에 사용됩니다
      url: "/reference_msi_custom_property_used_in_silent_installation.html"
    - title: SnapManager for Hyper-V는 호스트 또는 스토리지 시스템에서 라이센스가 부여되지 않습니다
      url: "/reference_snapmanager_for_hyper_v_is_not_licensed_on_the_host_or_in_the_storage_system.html"
    - title: 페일오버 후 백업을 삭제하는 중입니다
      url: "/reference_secondary_machine_unable_to_delete_backups_after_failover.html"
    - title: 백업 실패 후 스토리지 성능이 저하됩니다
      url: "/reference_storage_performance_degrades_after_failed_backup.html"
    - title: SnapInfo 스냅샷 복사본이 삭제되었습니다
      url: "/reference_retention_of_snapinfo_snapshot_copies.html"
    - title: 바이러스 백신 솔루션으로 인한 높은 메모리 소비
      url: "/reference_high_memory_consumption_caused_by_antivirus_solution.html"
    - title: 각 백업에 대해 2개의 스냅샷 복사본을 생성할 때의 공간 소비
      url: "/reference_space_consumption_when_making_two_snapshot_copies_for_each_backup.html"
    - title: 백업하는 동안 SnapDrive SDDiscoveryFileSystemListInfo 응답이 null입니다
      url: "/reference_error_snapdrive_sddiscoveryfilesystemlistinfo_response_is_null.html"
    - title: '오류: VSS 요청자 - 백업 구성 요소에 실패했습니다'
      url: "/reference_error_vss_requestor_backup_components_failed.html"
    - title: VSS 요청자 - 백업 구성 요소 실패. 예상 디스크가 시스템에 도착하지 않았습니다
      url: "/reference_error_vss_requestor_backup_components_failed_an_expected_disk_did_not_arrive_in_the_system.html"
    - title: VSS 요청자 - 부분 작성기 오류로 백업 구성 요소가 실패했습니다
      url: "/reference_dataset_backup_might_fail_with_a_partial_writer_error.html"
    - title: VSS는 NAS 백업 중에 Microsoft iSCSI Target VSS Hardware Provider에 대한 오류를 반환합니다
      url: "/reference_vss_returns_errors_against_microsoft_iscsi_target_vss_hardware_provider_during_nas_backup.html"
    - title: VSS 요청자 - 백업 구성 요소 실패. 스냅샷 세트 유지를 호출하지 못했습니다.
      url: "/reference_vss_requestor_backup_components_failed_failed_to_call_keep_snapshot_set.html"
    - title: SnapManager for Hyper-V에서 MBR LUN이 지원되지 않습니다
      url: "/reference_mbr_luns_unsupported_in_snapmanager_for_hyper_v.html"
    - title: Hyper-V Manager에서 가상 컴퓨터를 제거한 후 백업이 실패합니다
      url: "/reference_backup_fails_after_removing_virtual_machine_from_hyper_v_manager.html"
    - title: 일부 유형의 백업 실패는 부분 백업 실패를 초래하지 않습니다
      url: "/reference_some_types_of_failures_do_not_generate_error_message.html"
    - title: 스토리지 시스템 볼륨 이름 변경 후 복구 실패
      url: "/reference_restore_failure_after_storage_system_volume_renaming.html"
    - title: 페일백 후 백업에서 복원
      url: "/reference_restoring_from_a_backup_after_failback.html"
    - title: 데이터 세트를 새 노드로 업데이트하는 동안 웹 서비스 클라이언트 채널을 연결할 수 없습니다
      url: "/reference_web_service_client_channel_unable_to_connect_while_updating_the_dataset_to_the_new_node.html"
    - title: 데이터 세트는 Windows 페일오버 클러스터의 새 노드로 자동 복제되지 않습니다
      url: "/reference_datasets_are_not_automatically_replicated_to_new_nodes_in_a_windows_failover_cluster.html"
    - title: 오류 1935. 어셈블리 부품을 설치하는 동안 오류가 발생했습니다
      url: "/reference_error_1935_an_error_occurred_during_the_installation_of_assembly_component.html"
    - title: 동일한 스토리지 시스템에서 15개 이상의 CSV를 포함하는 백업 작업이 실패할 수 있습니다
      url: "/reference_backup_jobs_that_involve_more_than_15_csvs_from_the_same_filer_fail_with_rename_snapshot_error.html"
    - title: 지정된 VM이 없거나 온라인으로 백업할 수 없습니다
      url: "/reference_either_the_specified_vm_s_are_not_present_or_they_cannot_be_backed_up_online.html"
    - title: 필요한 핫픽스 KB2263829를 일부 플랫폼에 설치할 수 없습니다
      url: "/reference_required_hotfix_kb2263829_cannot_be_installed_on_some_platforms.html"
    - title: '"섀도우 복제본 생성이 이미 진행 중입니다." 오류와 함께 백업 실패'
      url: "/reference_backup_fail_with_the_error_shadow_copy_creation_is_already_in_progress.html"
