---
settings:
  name: SnapManager for Hyper-V
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: SnapManager for Hyper-V 문서
    url: "/index.html"
  - title: 릴리스 정보
    url: "/release-notes.html"
  - title: SnapManager for Hyper-V가 무엇인지
    url: "/concept-what-snapmanager-for-hyper-v-is.html"
    entries:
    - title: SnapManager for Hyper-V의 기능
      url: "/concept-what-you-can-do-with-snapmanager-for-hyper-v.html"
    - title: SnapManager for Hyper-V 제한 사항 목록입니다
      url: "/concept-snapmanager-for-hyper-v-limitations.html"
    - title: 데이터 관리 개념
      url: "/concept-data-management-concepts.html"
  - title: Hyper-V용 SnapManager 설치 요구 사항 목록
    url: "/reference-list-of-requirements-for-installing-snapmanager-for-hyper-v.html"
    entries:
    - title: ONTAP용 SnapManager Hyper-V 라이센스
      url: "/reference-snapmanager-for-hyper-v-licensing-for-ontap.html"
    - title: Hyper-V 상위 호스트 요구 사항
      url: "/reference-hyper-v-parent-host-requirements.html"
    - title: Windows Server 환경에 대한 핫픽스 요구 사항
      url: "/reference-hotfix-requirements-for-windows-server-environments.html"
    - title: 라이센스 요구 사항
      url: "/reference-license-requirements.html"
    - title: 원격 호스트 설치 마법사 사용에 대한 요구 사항
      url: "/reference-requirements-for-remote-host-install.html"
  - title: SnapManager for Hyper-V를 설치합니다
    url: "/concept-install-snapmanager-for-hyper-v.html"
    entries:
    - title: SnapManager for Hyper-V를 다운로드합니다
      url: "/task-download-snapmanager-for-hyper-v.html"
    - title: Windows용 SnapDrive 및 Hyper-V용 SnapManager 설치 순서
      url: "/concept-installation-order-for-snapdrive-for-windows-and-snapmanager-for-hyper-v.html"
    - title: SnapManager for Hyper-V를 설치합니다
      url: "/task-install-snapmanager-for-hyper-v.html"
    - title: 노드나 호스트에 SnapManager for Hyper-V를 원격으로 설치 또는 제거합니다
      url: "/task-remotely-install-or-uninstall-snapmanager-for-hyper-v-on-nodes.html"
    - title: 자동 설치를 위한 명령줄 스위치 목록 및 설명
      url: "/reference-command-line-switch-descriptions.html"
  - title: Windows에서 Hyper-V용 SnapManager를 제거합니다
    url: "/concept-uninstall-snapmanager-for-hyper-v-on-windows.html"
    entries:
    - title: SnapManager for Hyper-V를 제거합니다
      url: "/task-uninstall-snapmanager-for-hyper-v.html"
  - title: SnapManager for Hyper-V를 구성합니다
    url: "/concept-configure-snapmanager-for-hyper-v.html"
    entries:
    - title: 대시보드 설정
      url: "/concept-dashboard-settings.html"
    - title: 호스트를 구성합니다
      url: "/concept-configure-hosts.html"
      entries:
      - title: Hyper-V 상위 호스트 또는 호스트 클러스터를 추가하기 위한 요구 사항
        url: "/reference-requirements-for-adding-a-hyper-v-parent-host-or-host-cluster.html"
      - title: Hyper-V 상위 호스트 또는 호스트 클러스터를 추가합니다
        url: "/task-add-a-hyper-v-parent-host-or-host-cluster.html"
      - title: 저장소 연결 설정을 관리합니다
        url: "/task-manage-storage-connection-settings.html"
      - title: Hyper-V 상위 호스트 또는 호스트 클러스터를 봅니다
        url: "/task-view-a-hyper-v-parent-host-or-host-cluster.html"
      - title: 가상 머신을 봅니다
        url: "/task-view-a-virtual-machine.html"
      - title: Hyper-V 작업을 위한 SnapManager용 Hyper-V 가상 머신 마이그레이션
        url: "/task-migrate-a-hyper-v-virtual-machine-to-support-snapmanager-for-hyper-v-operations.html"
      - title: 호스트 및 데이터 세트 구성 정보를 가져오거나 내보냅니다
        url: "/task-import-or-export-host-and-dataset-configuration-information.html"
      - title: Hyper-V 상위 호스트 또는 상위 호스트 클러스터를 제거합니다
        url: "/task-remove-a-hyper-v-parent-host.html"
      - title: 이벤트 알림 설정
        url: "/concept-event-notification-settings.html"
        entries:
        - title: 이메일 알림을 구성합니다
          url: "/concept-configure-multiple-recipients-for-email-notifications-in-smhv.html"
      - title: 보고서 경로 설정
        url: "/concept-report-path-settings.html"
    - title: SnapInfo 디렉토리 설정을 구성합니다
      url: "/concept-configure-snapinfo-directory-settings.html"
      entries:
      - title: SnapInfo LUN을 설정합니다
        url: "/task-set-up-a-snapinfo-lun.html"
      - title: SnapInfo 디렉토리 경로를 변경합니다
        url: "/task-change-the-snapinfo-directory-path.html"
    - title: 데이터 세트를 구성합니다
      url: "/concept-configure-datasets.html"
      entries:
      - title: 데이터 세트 생성 요구 사항
        url: "/reference-requirements-for-creating-a-dataset.html"
      - title: 데이터 세트를 생성합니다
        url: "/task-create-a-dataset.html"
      - title: 데이터 세트를 수정합니다
        url: "/task-modify-a-dataset.html"
      - title: 데이터 세트 보기
        url: "/task-view-a-dataset.html"
      - title: 데이터 세트를 삭제합니다
        url: "/task-delete-a-dataset.html"
    - title: 정책을 구성합니다
      url: "/concept-configure-policies.html"
      entries:
      - title: 데이터 세트에 정책을 추가하기 위한 요구사항
        url: "/reference-requirements-for-adding-policies-to-a-dataset.html"
      - title: 정책 추가
        url: "/task-add-policies.html"
      - title: 정책을 수정합니다
        url: "/task-modify-policies.html"
      - title: 정책을 봅니다
        url: "/task-view-policies.html"
      - title: 정책을 삭제합니다
        url: "/task-delete-policies.html"
    - title: SMB를 통해 Hyper-V에 SVM 또는 CIFS 서버를 구성합니다
      url: "/concept-configure-svms-or-cifs-servers-for-hyper-v-over-smb.html"
  - title: 보고서 관리
    url: "/concept-report-management.html"
    entries:
    - title: 데이터 세트 보고서를 봅니다
      url: "/task-view-a-report.html"
    - title: 호스트 보고서를 봅니다
      url: "/task-view-a-host-report.html"
    - title: 보고서를 삭제합니다
      url: "/task-delete-a-report.html"
  - title: VSS 구성 요소
    url: "/concept-overview-of-vss-components.html"
    entries:
    - title: Windows Server 2012 이상에서 CSV 2.0
      url: "/concept-cluster-shared-volume-2-0-architecture.html"
    - title: Windows Server 2012에서 Hyper-V VM을 지원하는 SMB 3.0
      url: "/reference-smb-3-0-support-hyper-v-vms-in-windows-server-2012.html"
    - title: SnapManager for Hyper-V에서 VSS를 사용하는 방법
      url: "/concept-how-snapmanager-for-hyper-v-uses-vss.html"
    - title: ONTAP VSS 하드웨어 공급자 요구 사항
      url: "/concept-ontap-vss-hardware-provider-requirement.html"
    - title: 설치된 VSS 공급자를 봅니다
      url: "/task-view-installed-vss-providers.html"
    - title: VSS Hardware Provider가 성공적으로 사용되었는지 확인합니다
      url: "/task-verify-that-the-vss-hardware-provider-was-used-successfully.html"
  - title: SnapManager for Hyper-V에서 백업 작업을 생성하고 관리합니다
    url: "/concept-create-and-manage-backup-jobs-in-snapmanager-for-hyper-v.html"
    entries:
    - title: 데이터 세트를 수동으로 백업하기 위한 요구 사항입니다
      url: "/reference-requirements-for-manually-backing-up-a-dataset.html"
    - title: SnapManager for Hyper-V가 저장된 상태 백업을 처리하는 방법
      url: "/concept-how-snapmanager-for-hyper-v-handles-saved-state-backups.html"
    - title: 데이터 세트를 수동으로 백업합니다
      url: "/task-manually-backing-up-a-dataset.html"
    - title: 백업 작업을 모니터링합니다
      url: "/task-monitor-backup-jobs.html"
    - title: 백업을 삭제합니다
      url: "/task-delete-a-backup.html"
  - title: 백업 복제본에서 가상 머신을 복구합니다
    url: "/concept-restore-a-virtual-machine.html"
    entries:
    - title: 가상 머신 복구 요구 사항
      url: "/reference-requirements-for-restoring-a-virtual-machine.html"
    - title: 백업 복제본에서 가상 머신을 복구합니다
      url: "/task-restore-a-virtual-machine-from-a-backup-copy.html"
  - title: 클러스터 운영 체제 롤링 업그레이드를 수행합니다
    url: "/concept-perform-a-cluster-os-rolling-upgrade.html"
    entries:
    - title: 혼합 운영 체제 모드에서 LUN을 매핑합니다
      url: "/task-map-luns-after-the-windows-server-2016-node-addition.html"
    - title: 모든 노드에서 데이터 세트 및 SnapInfo를 업데이트합니다
      url: "/task-update-the-dataset-and-snapinfo-across-all-nodes.html"
  - title: 재해 복구를 수행합니다
    url: "/concept-perform-disaster-recovery.html"
    entries:
    - title: 페일오버에 Hyper-V용 SnapManager를 구성합니다
      url: "/concept-configure-snapmanager-for-hyper-v-for-failover.html"
    - title: 재해 복구 페일오버에서 복구 및 복원
      url: "/task-recover-and-restore-from-a-disaster-recovery-failover.html"
    - title: 재해 복구 페일백 후 스토리지 시스템을 재구성합니다
      url: "/task-reconfigure-storage-systems-after-a-disaster-recovery-failback.html"
    - title: 독립 실행형 호스트의 원래 구성을 복구합니다
      url: "/task-restore-the-original-configuration-for-standalone-hosts.html"
    - title: 클러스터된 호스트에 대한 원래 구성을 복구합니다
      url: "/task-restore-the-original-configuration-for-clustered-hosts.html"
  - title: SnapManager for Hyper-V의 문제를 해결합니다
    url: "/concept-snapmanager-for-hyper-v-troubleshoot.html"
    entries:
    - title: 다음 VM에 대한 백업이 실패하였습니다. 온라인 백업 또는 백업 대상 VM을 찾을 수 없기 때문입니다
      url: "/reference-backup-failed-for-the-following-vm-s-since-it-cannot-be-backedup-online-or-no-vm-to-be-found-for-backup.html"
    - title: IVssWriterCallback 인터페이스에 대한 예기치 않은 쿼리 오류. hr=0x80070005, 액세스가 거부되었습니다.
      url: "/reference-unexpected-error-querying-for-the-ivsswritercallback-interface-hr-0x80070005.html"
    - title: 백업 보고서는 보고서 이름에 관리 콘솔 시간대 정보를 사용합니다
      url: "/reference-backup-reports-use-management-console-time-zone-information-in-report-name.html"
    - title: IPv6 전용 환경에서는 백업 및 복원 알림이 전송되지 않습니다
      url: "/reference-backup-and-restore-notifications-not-sent-in-ipv6-only-environments.html"
    - title: 장애 조치 클러스터링 이벤트 ID 5121
      url: "/reference-failover-clustering-event-id-5121.html"
    - title: 복구 작업이 진행 중인 동안 생성된 가상 머신 백업이 잘못되었을 수 있습니다
      url: "/reference-virtual-machine-backups-made-while-a-restore-operation-is-in-progress-might-be-invalid.html"
    - title: 가상 시스템 관리
      url: "/reference-virtual-machine-adding-itself-to-a-dataset.html"
    - title: IPv6 전용 호스트에서는 연결 시간이 길어집니다
      url: "/reference-connection-time-is-longer-with-ipv6-only-host.html"
    - title: '볼륨 섀도 복사본 서비스 오류: 내부 불일치가 감지되었습니다'
      url: "/reference-volume-shadow-copy-service-error-an-internal-inconsistency-was-detected.html"
    - title: 웹 서비스 클라이언트 채널이 시스템 smhv51_81clus의 ConfigurationManagementService 인스턴스에
        연결할 수 없습니다
      url: "/reference-web-service-client-channel-was-unable-to-connect-to-the-configurationmanagementservice-instance-on-machine-smhv51-81clus.html"
    - title: MSI 사용자 정의 속성은 자동 설치에 사용됩니다
      url: "/reference-msi-custom-property-used-in-silent-installation.html"
    - title: SnapManager for Hyper-V는 호스트 또는 스토리지 시스템에서 라이센스가 부여되지 않습니다
      url: "/reference-snapmanager-for-hyper-v-is-not-licensed-on-the-host-or-in-the-storage-system.html"
    - title: 페일오버 후 백업을 삭제합니다
      url: "/reference-secondary-machine-unable-to-delete-backups-after-failover.html"
    - title: 백업 실패 후 스토리지 성능이 저하됩니다
      url: "/reference-storage-performance-degrades-after-failed-backup.html"
    - title: SnapInfo 스냅샷 복사본이 삭제되었습니다
      url: "/reference-retention-of-snapinfo-snapshot-copies.html"
    - title: 바이러스 백신 솔루션으로 인한 높은 메모리 소비
      url: "/reference-high-memory-consumption-caused-by-antivirus-solution.html"
    - title: 각 백업에 대해 2개의 스냅샷 복사본을 생성할 때의 공간 소비
      url: "/reference-space-consumption-when-making-two-snapshot-copies-for-each-backup.html"
    - title: 백업하는 동안 SnapDrive SDDiscoveryFileSystemListInfo 응답이 null입니다
      url: "/reference-error-snapdrive-sddiscoveryfilesystemlistinfo-response-is-null.html"
    - title: '오류: VSS 요청자 - 백업 구성 요소에 실패했습니다'
      url: "/reference-error-vss-requestor-backup-components-failed.html"
    - title: VSS 요청자 - 백업 구성 요소 실패. 예상 디스크가 시스템에 도착하지 않았습니다
      url: "/reference-error-vss-requestor-backup-components-failed-an-expected-disk-did-not-arrive-in-the-system.html"
    - title: VSS 요청자 - 부분 작성기 오류로 백업 구성 요소가 실패했습니다
      url: "/reference-dataset-backup-might-fail-with-a-partial-writer-error.html"
    - title: VSS는 NAS 백업 중에 Microsoft iSCSI Target VSS Hardware Provider에 대한 오류를 반환합니다
      url: "/reference-vss-returns-errors-against-microsoft-iscsi-target-vss-hardware-provider-during-nas-backup.html"
    - title: VSS 요청자 - 백업 구성 요소 실패. 스냅샷 세트 유지를 호출하지 못했습니다.
      url: "/reference-vss-requestor-backup-components-failed-failed-to-call-keep-snapshot-set.html"
    - title: SnapManager for Hyper-V에서 MBR LUN이 지원되지 않습니다
      url: "/reference-mbr-luns-unsupported-in-snapmanager-for-hyper-v.html"
    - title: Hyper-V Manager에서 가상 컴퓨터를 제거한 후 백업이 실패합니다
      url: "/reference-backup-fails-after-removing-virtual-machine-from-hyper-v-manager.html"
    - title: 일부 유형의 백업 실패는 부분 백업 실패를 초래하지 않습니다
      url: "/reference-some-types-of-failures-do-not-generate-error-message.html"
    - title: 스토리지 시스템 볼륨 이름 변경 후 복구 실패
      url: "/reference-restore-failure-after-storage-system-volume-renaming.html"
    - title: 페일백 후 백업에서 복원합니다
      url: "/reference-restore-from-a-backup-after-failback.html"
    - title: 데이터 세트를 새 노드로 업데이트하는 동안 웹 서비스 클라이언트 채널을 연결할 수 없습니다
      url: "/reference-web-service-client-channel-unable-to-connect-while-updating-the-dataset-to-the-new-node.html"
    - title: 데이터 세트는 Windows 페일오버 클러스터의 새 노드로 자동 복제되지 않습니다
      url: "/reference-datasets-are-not-automatically-replicated-to-new-nodes-in-a-windows-failover-cluster.html"
    - title: 오류 1935. 어셈블리 부품을 설치하는 동안 오류가 발생했습니다
      url: "/reference-error-1935-an-error-occurred-during-the-installation-of-assembly-component.html"
    - title: 동일한 스토리지 시스템에서 15개 이상의 CSV를 포함하는 백업 작업이 실패할 수 있습니다
      url: "/reference-backup-jobs-that-involve-more-than-15-csvs-from-the-same-filer-fail-with-rename-snapshot-error.html"
    - title: 지정된 VM이 없거나 온라인으로 백업할 수 없습니다
      url: "/reference-either-the-specified-vm-s-are-not-present-or-they-cannot-be-backed-up-online.html"
    - title: 필요한 핫픽스 KB2263829를 일부 플랫폼에 설치할 수 없습니다
      url: "/reference-required-hotfix-kb2263829-cannot-be-installed-on-some-platforms.html"
    - title: '"섀도우 복제본 생성이 이미 진행 중입니다." 오류와 함께 백업 실패'
      url: "/reference-backup-fail-with-the-error-shadow-copy-creation-is-already-in-progress.html"
  - title: 법적 고지
    url: "/legal-notices.html"
