---
permalink: reference_space_consumption_when_making_two_snapshot_copies_for_each_backup.html 
sidebar: sidebar 
keywords: space, consumption, snapshot, copies, copy, backup 
summary: 각 백업에 대해 2개의 스냅샷 복사본을 생성할 때의 공간 소비 
---
= 각 백업에 대해 2개의 스냅샷 복사본을 생성할 때의 공간 소비
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* * 문제 *
+
Hyper-V 개체가 포함된 모든 백업에 대해 2개의 스냅샷 복사본이 생성되는데, 이는 공간 소비에 대한 우려로 이어질 수 있습니다.

+

NOTE: 이는 애플리케이션 정합성 보장 백업에만 적용됩니다.

* * 원인 *
+
Microsoft Hyper-V VSS 작성기는 VM 내에서 VM과 애플리케이션 정합성이 보장되는 백업 복제본을 모두 생성하고 VHD에 상주하는 애플리케이션을 사용합니다. 소프트웨어 정합성 보장 및 VM 정합성 보장 백업 복제본을 모두 생성하기 위해 VSS는 기본 자동 복구 프로세스를 사용하여 VM을 소프트웨어 스냅샷 복사본과 일치하는 상태로 설정합니다. Hyper-V VSS 기록기는 백업의 각 VM에 접촉하고 소프트웨어 정합성이 보장되는 스냅샷 복사본을 생성합니다.

+
스냅샷 복사본이 생성된 후 상위 파티션은 이러한 VM이 포함된 전체 디스크(LUN)의 VSS 스냅샷 복사본을 생성합니다. 상위 파티션 스냅샷 복사본이 생성된 후 VSS는 이전에 생성된 상위 파티션을 마운트하고, 각 VM을 소프트웨어 정합성 보장 상태로 롤백하고, 소프트웨어 스냅샷 복사본이 생성된 후 VM에 대한 변경 사항을 제거해야 합니다. VHD에 대한 이러한 수정 사항은 영구적으로 이루어져야 합니다. 이러한 스냅샷 복사본은 기본적으로 읽기 전용이므로 업데이트된 VHD 복사본을 유지하려면 새 스냅샷 복사본을 만들어야 합니다. 이러한 이유로 볼륨의 두 번째 스냅샷 복사본이 생성됩니다. 이 스냅샷 복사본은 접미사 *_backup * 으로 표시되며 복원 작업에 사용되는 백업 복사본입니다.

* * 시정 조치 *
+
2개의 스냅샷 복사본은 쌍으로 간주됩니다. 백업에 대한 보존 기간이 종료되면 두 스냅샷 복사본이 모두 삭제됩니다. 복원 작업에 필요한 첫 번째 스냅샷 복사본이 수동으로 삭제되어서는 안 됩니다.

+
Microsoft VSS는 CSV(Cluster Shared Volume)를 소유한 호스트에서만 VM 백업을 지원하므로 CSV 소유권이 노드 간에 이동하여 클러스터의 각 호스트에 있는 VM의 백업을 생성합니다.

+
CSV를 백업할 때 SnapManager for Hyper-V는 클러스터에서 호스트당 두 개의 스냅샷 복사본을 생성하며, 이 스냅샷 복사본은 해당 CSV에서 VM을 실행합니다. 즉, 단일 CSV에서 15개의 VM을 백업하고 해당 VM이 3개의 Hyper-V 서버에 균등하게 분할된 경우 백업당 총 6개의 Snapshot 복사본이 있습니다.


