---
permalink: reference_requirements_for_manually_backing_up_a_dataset.html 
sidebar: sidebar 
keywords: backup, dataset, manual, first, name, describe, type, option, retention, policy, requirement 
summary: 데이터 세트를 수동으로 백업하려면 먼저 데이터 세트의 이름과 설명을 입력하고 백업 유형 및 옵션을 선택한 다음 보존 정책을 설정해야 합니다. 
---
= 데이터 세트를 수동으로 백업하기 위한 요구 사항입니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
데이터 세트를 수동으로 백업하려면 먼저 데이터 세트의 이름과 설명을 입력하고 백업 유형 및 옵션을 선택한 다음 보존 정책을 설정해야 합니다.



== 백업 이름 및 설명입니다

백업에 이름과 설명을 할당해야 합니다.

백업의 기본 명명 규칙은 DataSetName_Timestamp 입니다. 항상 백업 이름의 일부로 표시되는 타임스탬프를 제외한 백업 이름의 모든 항목을 변경할 수 있습니다.

백업 이름과 설명은 다음 문자로 제한됩니다.

* a ~ z
* A에서 Z
* 0에서 9
* _ (밑줄)
* 하이픈




== 정책 선택

필요 시 백업에 사용할 정책을 결정해야 합니다.

백업 마법사에서 특정 정책을 선택할 수 있습니다. 정책 자체를 변경하지 않고 정책과 연결된 스크립트뿐만 아니라 보존 또는 복제 정책을 재정의할 수 있습니다.

없음 을 선택할 수도 있습니다. 이 옵션을 사용하면 정책을 만들지 않고도 필요 시 백업을 수행할 수 있습니다. 이 옵션은 보존 정책, 복제 정책 및 스크립트의 기본값을 사용합니다.



== 보존 값

선택한 정책에 지정된 보존 정책을 재정의할 수 있습니다. 이 경우 삭제하기 전에 시간 단위, 일 단위, 주 단위, 월 단위 또는 무제한 백업 복사본을 유지할 최소 시간을 결정해야 합니다.

시간 또는 지정된 백업 수에 따라 백업을 유지할 수 있습니다. 예를 들어 최신 백업 10개를 유지하거나 15일이 지난 백업을 삭제할 수 있습니다.



== 백업 유형입니다

애플리케이션 정합성 보장 또는 충돌 시에도 정합성 보장 백업을 수행할 수 있습니다.



== 백업 옵션

저장된 상태 백업을 허용할 수 있습니다.

SnapManager for Hyper-V의 기본 동작은 하나 이상의 가상 머신을 온라인으로 백업할 수 없는 경우 백업에 실패하는 것입니다. 가상 머신이 Saved(저장됨) 상태이거나 종료된 경우 온라인 백업을 수행할 수 없습니다. 경우에 따라 가상 머신이 Saved(저장됨) 상태에 있거나 유지 보수를 위해 종료되었지만 온라인 백업이 불가능한 경우에도 백업을 계속 진행해야 합니다. 이렇게 하려면 저장된 상태의 가상 머신을 이동하거나 저장된 상태 백업을 허용하는 정책이 있는 다른 데이터 세트로 종료할 수 있습니다.

또한 Allow saved state VM backup 확인란을 선택하여 기존 정책을 수정할 수도 있습니다. 이를 통해 SnapManager for Hyper-V는 저장된 상태의 가상 머신을 백업할 수 있습니다. 이 옵션을 선택하면 Hyper-V VSS 기록기가 가상 머신을 저장된 상태로 백업하거나 가상 머신의 오프라인 백업을 수행할 때 SnapManager for Hyper-V가 백업에 실패합니다. 저장된 상태 또는 오프라인 백업을 수행하면 다운타임이 발생할 수 있습니다.

분산된 애플리케이션 정합성이 보장되는 백업 기능을 사용하면 파트너 클러스터 노드에서 실행되는 여러 VM이 백업 노드에서 생성된 단일 하드웨어 스냅샷 복사본의 일관성을 유지할 수 있습니다. 이 기능은 Windows 페일오버 클러스터의 여러 노드에서 CSV 2.0 Windows 볼륨에서 실행되는 모든 VM에 대해 지원됩니다.



== SnapMirror 백업의 2차 스토리지

이러한 옵션을 사용하면 SnapMirror 관계에 정의된 보조 스토리지에 적용할 수 있는 옵션을 적용할 수 있습니다. 백업 후 * SnapMirror 업데이트 * 를 선택할 수 있습니다. 볼트 라벨 옵션 창 아래에서 * 백업 후 SnapVault 업데이트 * 를 선택할 수 있습니다. 백업 후 SnapVault 업데이트 * 를 선택한 경우, 드롭다운 메뉴에서 볼트 라벨을 선택하거나 사용자 정의 라벨을 입력해야 합니다.



== 백업 스크립트

선택한 정책에 지정된 스크립트 옵션을 재정의할 수 있습니다.

스크립트에 특정 호스트를 지정하지 않는 한 이러한 스크립트는 모든 데이터 세트 구성원 호스트에서 실행됩니다.

* 관련 정보 *

http://technet.microsoft.com/library/cc753637(WS.10).aspx["Microsoft TechNet: Hyper-V"]

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-buvault/home.html["SnapVault Express를 사용한 ONTAP 9 볼륨 백업 가이드"]
