---
permalink: reference_requirements_for_restoring_a_virtual_machine.html 
sidebar: sidebar 
keywords: restore, virtual, machine, backup, copy, requirement 
summary: 백업 복제본에서 가상 머신을 복구하려면 먼저 백업 복제본을 복구할 방법을 결정해야 합니다. 
---
= 가상 머신 복구 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
백업 복제본에서 가상 머신을 복구하려면 먼저 백업 복제본을 복구할 방법을 결정해야 합니다.



== VM 백업 복제본 이름입니다

복원할 백업 복사본을 결정해야 합니다.

모든 백업 복사본은 Recovery Management 창의 Backups 창에 이름별로 나열됩니다.



== VM 백업 복제본 유형입니다

애플리케이션 정합성이 보장되는 백업에서 VM을 복구하는 작업은 VSS와 조율하여 수행됩니다. Hyper-V VSS writer는 복원 작업이 완료된 후 VM을 복원하기 전에 VM을 삭제하고 Hyper-V Manager에 등록합니다.

충돌 시에도 정합성 보장 백업에서 VM을 복원하는 것은 VSS와 관련이 없습니다. 복구 작업 전에 VM이 꺼져 있습니다. 충돌 시에도 정합성 보장 백업에서 복원하는 경우 VM이 존재해야 하며 충돌 시에도 정합성 보장 백업에서 삭제된 VM을 복원하지 못합니다.



== VM 백업 복사 상태입니다

가상 머신이 아직 있는지 확인해야 합니다.

가상 머신이 더 이상 존재하지 않는 경우에도 가상 머신이 생성된 LUN이 여전히 존재할 경우 가상 머신을 복구할 수 있습니다. LUN은 백업 시와 드라이브 문자 및 Windows 볼륨 GUID가 같아야 합니다.

Windows Server 2008 R2에서 가상 머신을 삭제하면 애플리케이션 정합성이 보장되는 백업에서 가상 머신을 복구할 수 있지만, Windows Server 2012 및 Windows Server 2012 R2에서는 충돌 및 애플리케이션 정합성이 보장되는 백업 모두에서 삭제된 가상 머신을 복구할 수 있습니다.

가상 머신이 삭제되기 전에 모든 데이터 세트에서 제거된 경우에도 보호되지 않은 리소스를 선택하고 가상 머신이 속한 백업을 선택하여 가상 머신을 복원할 수 있습니다.



== VM 백업 복제본 구성 상태입니다

가상 머신 구성이 백업 시점의 구성과 동일한지 확인해야 합니다.

현재 가상 머신 구성이 백업 시점과 다른 경우, SnapManager for Hyper-V는 가상 머신 레이아웃이 변경되었음을 알리고 백업에 존재했던 가상 머신 구성 및 데이터를 복원할 것인지 묻습니다.


NOTE: SnapManager for Hyper-V는 가상 머신의 클러스터 구성을 백업하지 않으므로 클러스터 구성을 복원할 수 없습니다. 가상 머신 및 클러스터 구성이 손실되면 SnapManager for Hyper-V에서 가상 머신을 복구할 수 있지만, 고가용성을 수동으로 설정해야 합니다.

가상 머신이 백업에 포함된 가상 머신의 현재 구성과 다르게 구성된 경우 새로 추가되거나 제거된 가상 하드 디스크(VHD)를 반영하도록 클러스터 구성을 업데이트해야 할 수 있습니다.



== 스냅샷 복사 상태입니다

복구 작업을 시도하기 전에 스토리지 시스템에 백업 스냅샷 복사본이 있는지 확인할 수 있습니다.



== VM을 다시 시작합니다

가상 머신이 복구된 후 시작하도록 선택할 수 있습니다.

* 관련 정보 *

http://technet.microsoft.com/library/ff182338(v=WS.10).aspx["Microsoft TechNet: Windows Server 2008 R2의 장애 조치 클러스터"]
