---
permalink: reference-error-vss-requestor-backup-components-failed.html 
sidebar: sidebar 
keywords: error, vss, requestor, backup, component, fail 
summary: '오류: VSS 요청자 - 백업 구성 요소에 실패했습니다.' 
---
= 오류: VSS 요청자 - 백업 구성 요소에 실패했습니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* * 메시지 *
+
SnapManager for Hyper-V 보고서 및 Windows 이벤트 로그에 "Error: VSS Requestor - Backup Components failed. 백업 또는 복구와 관련된 writer Microsoft Hyper-V VSS 작성기에서 다시 수행할 수 있는 오류가 발생했습니다. writer가 오류 코드 0x800423f3을 반환했습니다. writer 상태는 XXX입니다. 자세한 내용은 Windows 이벤트 뷰어의 Hyper-V-VMMS 이벤트 로그를 참조하십시오

* * 설명 *
+
애플리케이션 정합성 보장 백업이 실패하는 VSS 재시도 오류가 발생하면 SnapManager for Hyper-V는 각 시도 사이에 1분 정도 기다리면서 백업을 3회 재시도합니다.

* * 시정 조치 *
+
다음 레지스트리 키를 사용하여 재시도 횟수(재시도 횟수)와 재시도 간의 대기 시간(재시도 간격)을 구성할 수 있습니다.

+
"키: HKLM\System\CurrentControlSet\Services\OnCommandHyperV\Parameters DWORD 값(초): VSS_RETRY_SLEEP(재시도 간 대기 시간) DWORD 값: VSS_RETRY(재시도 횟수)

+
이러한 설정은 Hyper-V 호스트 레벨에 있으며 키와 값은 각 가상 머신에 대해 Hyper-V 호스트에서 설정해야 합니다. 가상 머신이 클러스터링되어 있는 경우 클러스터의 각 노드에서 키를 설정해야 합니다.

+
이러한 레지스트리 키를 변경하거나 추가한 후에는 Hyper-V용 SnapManager를 다시 시작해야 합니다.


