---
permalink: reference-command-line-switch-descriptions.html 
sidebar: sidebar 
keywords: command, line, switch, perform, silent, installation, enable, script, snapmanager, hyper-v 
summary: 명령줄 스위치를 사용하여 자동 설치를 수행할 수 있습니다. 이 경우 설치 스크립트를 사용하여 SnapManager for Hyper-V를 설치할 수 있습니다 
---
= 자동 설치를 위한 명령줄 스위치 목록 및 설명
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
명령줄 스위치를 사용하여 자동 설치를 수행할 수 있습니다. 이 경우 설치 스크립트를 사용하여 SnapManager for Hyper-V를 설치할 수 있습니다

다음 표에서는 값 목록을 제공하고 사용 가능한 각 명령줄 설치 스위치에 대해 설명합니다.

|===
| 스위치 | 값 | 설명 


 a| 
silent_mode =
 a| 
1
 a| 
SnapManager for Hyper-V가 자동 설치 기능을 올바르게 실행할 수 있도록 합니다. 이 스위치는 최초 설치, 업그레이드 및 전체 설치 해제에 필요합니다.



 a| 
REINSTALLMODE =
 a| 
 a| 
사용할 재설치 모드를 지정합니다.



 a| 
REINSTALLMODE =
 a| 
V
 a| 
소스 패키지에서 설치가 실행되고 로컬 패키지가 캐시됨을 나타냅니다. Hyper-V용 SnapManager를 처음 설치할 때는 이 옵션을 사용하지 마십시오 버전, 날짜 또는 체크섬 값에 관계없이 모든 파일을 다시 설치합니다.



 a| 
REINSTALLMODE =
 a| 
A
 a| 
이전 버전이 있거나 파일이 누락된 경우 Hyper-V용 SnapManager 파일을 다시 설치합니다.



 a| 
REINSTALLMODE =
 a| 
o
 a| 
HKEY_LOCAL_MACHINE 및 HKEY_CLASSES_ROOT의 Hyper-V용 모든 SnapManager에 필요한 레지스트리 항목을 다시 작성해야 함을 나타냅니다.



 a| 
REINSTALLMODE =
 a| 
M
 a| 
HKEY_CURRENT_USER 및 HKEY_USERS의 Hyper-V에 필요한 모든 SnapManager 레지스트리 항목을 다시 작성해야 함을 나타냅니다.



 a| 
REINSTALLMODE =
 a| 
U
 a| 
모든 바로 가기를 다시 설치하고 모든 아이콘을 다시 설치하며 기존 바로 가기 및 아이콘을 덮어씁니다.



 a| 
재설치 =
 a| 
모두
 a| 
모든 Hyper-V용 SnapManager 기능을 다시 설치합니다.



 a| 
/LI
 a| 
파일 이름
 a| 
SnapDrive 설치 로그를 생성하도록 지정합니다.



 a| 
SMHV_LICENSE =
 a| 
라이센스
 a| 
Hyper-V에 대해 적절하고 유효한 SnapManager 라이센스를 지정합니다.



 a| 
INSTALLDIR=
 a| 
대상 설치 디렉토리
 a| 
SnapManager for Hyper-V가 설치되는 타겟 설치 디렉토리를 지정합니다. 이 스위치는 SnapManager for Hyper-V를 처음 설치할 때만 필요합니다.



 a| 
SV고객 이름 =
 a| 
도메인\사용자 이름
 a| 
SnapManager for Hyper-V가 무인 설치 중에 사용하는 도메인 및 사용자 이름을 지정합니다.



 a| 
SMHVSRV_PASSWORD =
 a| 
암호
 a| 
SMHVSRV_PASSWORD 사용자의 암호를 지정합니다.



 a| 
SMHVSRV_CONFIRMUSERPASSWORD =
 a| 
암호
 a| 
SMHVSRV_CONFIRMUSERPASSWORD 사용자의 암호를 확인합니다.



 a| 
SMHV_WEBSRV_TCP_PORT
 a| 
포트 번호입니다
 a| 
Net.tcp에 SnapManager for Hyper-V 웹 서비스가 사용하는 포트를 지정합니다. 기본 포트는 808입니다.

|===
다음 구문은 새로 설치하는 방법을 보여 줍니다.

'etup.exe /s /v"/qn silent_mode=1/L * v SMHVInstall.log SVCUSERNAME=Domain\User Name SMHVSRV_PASSWORD=password SMHVSRV_CONFIRMUSERPASSWORD=password"'를 입력합니다

다음 구문은 업그레이드를 보여 줍니다.

S etup.exe /s /v"/qn REINSTALLMODE=vamus reinstall=all silent_mode=1/L * v SMHVUpgrade.log SVCUSERNAME=Domain\User Name SMHVSRV_password=password SMHVSRV_CONFIRMUSERPASSWORD=password""를 입력합니다

다음 구문은 설치 제거를 보여 줍니다.

'etup.exe /s/x/v"/qn silent_mode=1/L * v SMHVuninstall.log"
