---
permalink: reference-list-of-requirements-for-installing-snapmanager-for-hyper-v.html 
sidebar: sidebar 
keywords: environment, hardware, software, ontap, license, licensing, requirement, install, snapmanager, hyper-v, windows, .net, 4.5 
summary: SnapManager for Hyper-V를 설치하기 전에 사용자 환경이 모든 하드웨어, 소프트웨어, ONTAP 및 라이센스 요구 사항을 충족해야 합니다 
---
= Hyper-V용 SnapManager 설치 요구 사항 목록
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
SnapManager for Hyper-V를 설치하기 전에 사용자 환경이 모든 하드웨어, 소프트웨어, ONTAP 및 라이센스 요구 사항을 충족해야 합니다 최소 Windows 운영 체제 및 .Net 4.5에 대한 요구 사항이 충족되지 않으면 설치 프로그램이 중지됩니다.



== Hyper-V 상위 호스트 요구 사항

Windows Server 2008 R2 이상을 실행하는 Hyper-V 상위 호스트가 있어야 합니다. 상위 호스트에서 Hyper-V 역할을 사용하도록 설정해야 합니다. Hyper-V 상위 호스트에 Windows용 SnapDrive 7.1 이상이 설치되어 있어야 합니다.



== SnapManager for Hyper-V 다운로드

NetApp Support 사이트에서 SnapManager for Hyper-V 소프트웨어를 다운로드해야 합니다.



== 수행할 수 있습니다

스토리지 시스템에서 적절한 버전의 ONTAP 소프트웨어를 실행해야 합니다. 호스트 기반 또는 스토리지 시스템 라이센스를 사용하여 SnapManager for Hyper-V를 설치할 수 있습니다



== 추가 수익 실적을

SnapManager for Hyper-V를 실행하려면 적절한 라이센스가 있어야 합니다



== 자격 증명

Hyper-V용 SnapManager를 설치하고 실행하려면 적절한 자격 증명이 있어야 합니다



== 서비스 계정 및 인증 요구 사항

서비스 계정이 있어야 하며 인증 요구 사항을 충족해야 합니다. 서비스 계정을 사용하여 호스트에 로그인할 수 있어야 하며 해당 계정에 관리 권한이 있어야 합니다.



== 웹 서비스 포트 번호입니다

웹 서비스 Net.tcp 포트 번호를 사용할 수 있어야 합니다. 기본 포트 번호는 808입니다. 클러스터에 SnapManager for Hyper-V를 설치할 때 모든 노드에서 동일한 포트 번호를 사용해야 합니다.
