---
permalink: reference_requirements_for_creating_a_dataset.html 
sidebar: sidebar 
keywords: specific, requirement, create, dataset, protect, data, host, cluster, snapmanager, hyper-v 
summary: 데이터 세트를 생성하여 데이터를 보호하려면 특정 요구사항을 충족해야 합니다. 
---
= 데이터 세트 생성 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
데이터 세트를 생성하여 데이터를 보호하려면 특정 요구사항을 충족해야 합니다. 먼저 Hyper-V용 SnapManager에 호스트 또는 호스트 클러스터를 추가한 다음 호스트 또는 호스트 클러스터에 가상 머신을 추가해야 합니다.



== 데이터 세트 이름 및 설명

데이터 세트의 이름을 지정할 때 사이트에서 명명 규칙을 사용하여 관리자가 데이터 세트를 찾고 식별할 수 있도록 해야 합니다. 이러한 문자는 다음과 같습니다.

* a ~ z
* A에서 Z
* 0에서 9
* _ (밑줄)
* 하이픈




== 데이터 세트 리소스

가상 머신 등의 리소스를 데이터 세트에 추가하기 전에 Hyper-V용 SnapManager에 호스트 또는 호스트 클러스터를 추가해야 합니다.

호스트, 전용 가상 머신 또는 공유 가상 머신을 데이터 세트에 추가할 수 있습니다. 호스트를 추가하는 경우 호스트에 속한 모든 가상 시스템을 추가합니다. 다른 호스트에 속하는 가상 머신을 데이터 세트에 추가할 수도 있습니다. 가상 시스템은 여러 데이터 세트에 속할 수 있습니다.


NOTE: 동일한 호스트 클러스터에 속한 전용 및 공유 가상 머신은 동일한 데이터 세트에 존재하지 않아야 합니다. 이러한 유형의 리소스를 단일 데이터 세트에 추가하면 데이터 세트 백업이 실패할 수 있습니다.



== 가상 머신 및 ONTAP LUN

구성 파일, 스냅샷 복사본 및 VHD를 비롯하여 가상 머신과 관련된 모든 파일이 ONTAP LUN에 상주해야 합니다.



== 데이터 세트 리소스 사용

애플리케이션 정합성이 보장되는 백업 작업은 항상 호스트에서 한 번만 수행할 수 있습니다. 동일한 가상 머신이 다른 데이터 세트에 속해 있는 경우 애플리케이션 정합성이 보장되는 데이터 세트 백업을 동시에 예약해서는 안 됩니다. 이 경우 백업 작업 중 하나가 실패합니다.

데이터 세트를 생성할 때는 특정 ONTAP LUN에 있는 모든 가상 머신을 선택해야 합니다. 따라서 하나의 스냅샷 복사본에 모든 백업을 만들고 스토리지 시스템의 공간 사용을 줄일 수 있습니다.
