---
permalink: reference-requirements-for-remote-host-install.html 
sidebar: sidebar 
keywords: remote, host, install, wizard, snapmanager, hyper-v, host, node, require, detail, requirement 
summary: 원격 호스트 설치 마법사를 사용하여 호스트 또는 노드에 SnapManager for Hyper-V를 원격으로 설치하기 전에 필요한 호스트 세부 정보를 수집해야 합니다. 
---
= 원격 호스트 설치 마법사 사용에 대한 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
원격 호스트 설치 마법사를 사용하여 호스트 또는 노드에 SnapManager for Hyper-V를 원격으로 설치하기 전에 필요한 호스트 세부 정보를 수집해야 합니다.

보호 창의 작업 창에서 원격 호스트 설치 마법사에 액세스할 수 있습니다. 독립 실행형 및 클러스터 노드 또는 호스트에 SnapManager for Hyper-V를 원격으로 설치하거나 제거할 수 있습니다.

SnapManager for Hyper-V가 없는 호스트를 추가하는 경우 호스트 추가 마법사에서 호스트에 설치하라는 메시지를 표시합니다.

* * 설치 또는 제거 *
+
마법사를 사용하여 호스트나 노드에서 SnapManager for Hyper-V를 원격으로 설치하거나 제거할 것인지 선택해야 합니다.

* * 서버당 또는 스토리지당 *
+
서버당 SnapManager for Hyper-V를 설치할지 또는 스토리지별로 설치할지를 선택해야 합니다.

* * 호스트 이름/IP *
+
SnapManager for Hyper-V를 설치할 호스트의 이름 또는 IP 주소를 제공해야 합니다 찾아보기... * 를 선택하여 호스트 또는 노드를 찾을 수 있습니다.

* * 포트 *
+
호스트 또는 노드에 연결할 포트 번호를 제공해야 합니다.

* * SMHV 라이센스 키 *
+
Hyper-V용 SnapManager 라이센스 키를 제공해야 합니다.

* * SDW 라이센스 키 *
+
Windows용 SnapDrive 라이센스 키를 제공해야 합니다.

* * 사용자 이름 *
+
format_domain\username_을 사용하여 호스트 또는 노드 관리자 수준의 사용자 이름을 제공해야 합니다.

* * 암호 *
+
호스트 또는 노드 암호를 입력해야 합니다.

* * 암호 확인 *
+
확인을 위해 호스트 또는 노드 암호를 다시 입력해야 합니다.


