---
permalink: task_restoring_a_virtual_machine_from_a_backup_copy.html 
sidebar: sidebar 
keywords: snapmanager, hyper-v, restore, single, virtual, machine, vm, recover, lost, damage, data, backup, copy, restoring 
summary: 'Hyper-V용 SnapManager를 사용하면 한 번에 단일 가상 머신(VM)을 복원하여 백업 복사본에서 손실되거나 손상된 데이터를 복구할 수 있습니다.' 
---
= 백업 복제본에서 가상 머신 복구
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Hyper-V용 SnapManager를 사용하면 한 번에 단일 가상 머신(VM)을 복원하여 백업 복사본에서 손실되거나 손상된 데이터를 복구할 수 있습니다.

다음 정보를 사용할 수 있어야 합니다.

* 백업 이름입니다
* 구성 정보
* 스크립트 정보


대체 호스트로 복원할 때 원래 VM이 있는 물리적 컴퓨터의 CPU 유형은 VM을 복원하려는 물리적 컴퓨터와 호환되어야 합니다. 또는 Hyper-V Manager를 사용하여 다른 CPU 유형의 시스템으로 시스템을 복원할 수 있도록 지정할 수 있습니다.

스토리지 실시간 마이그레이션 후에는 최신 백업에서 복원할 수 없습니다.

Hyper-V 가상 머신의 복구 작업을 시작하고 동일한 가상 머신의 또 다른 백업 또는 복구가 진행 중인 경우 작업이 실패합니다.

. 탐색 창에서 * 복구 * 를 클릭합니다.
. 복구할 가상 머신을 선택합니다.
. 백업 창에서 복원할 백업 복사본의 이름을 선택하고 * 복원 * 을 클릭합니다.
+
복원 마법사가 나타납니다.

. 마법사의 단계를 완료하여 가상 머신 백업 복사본을 복구합니다.
+
마법사를 닫아도 복원 작업은 취소되지 않습니다. Hyper-V용 SnapManager는 복구 작업을 시작하기 전에 가상 머신 구성을 검증합니다. 가상 머신 구성에 변경 사항이 있으면 작업을 계속할지 또는 취소할지 선택할 수 있는 경고가 나타납니다.



작업 관리 창에서 복구 작업의 상태를 보거나 보고서 관리 창에서 보고서를 확인하여 작업 결과를 확인할 수 있습니다.

* 관련 정보 *

xref:reference_restoring_from_a_backup_after_failback.adoc[페일백 후 백업에서 복원]
